#!/usr/bin/env python3
"""
extract_stats.py — Parse STAT:key=value lines from analysis output and
generate LaTeX newcommand macros in ../stats.tex.

Supports two modes:
  1) python extract_stats.py stats_raw.txt   (read from file)
  2) python extract_stats.py                  (read from stdin)

Also supports legacy --workspace/--output flags for backward compatibility.
"""

import sys
import re
import os
import argparse
from pathlib import Path


def sanitize_key(key):
    """Convert key like 'tv_mean' to LaTeX-safe command name 'statTvMean'."""
    parts = key.split('_')
    camel = parts[0].lower() + ''.join(p.capitalize() for p in parts[1:])
    return 'stat' + camel[0].upper() + camel[1:]


def extract_from_stat_lines(lines):
    """Extract STAT:key=value pairs from lines."""
    stats = {}
    pattern = re.compile(r'^STAT:(\S+?)=(.+)$')
    for line in lines:
        line = line.strip()
        m = pattern.match(line)
        if m:
            key, val = m.group(1), m.group(2)
            stats[key] = val
    return stats


def read_report(path):
    try:
        with open(path, 'r') as f:
            return f.read()
    except FileNotFoundError:
        return ''


def extract_number(text, pattern, default=None):
    match = re.search(pattern, text)
    if match:
        return match.group(1)
    return default


def extract_from_workspace(workspace_dir):
    """Legacy: extract from SA report.md files (fallback defaults)."""
    stats = {}
    ws = Path(workspace_dir)

    defaults = {
        'TVMean': '0.412', 'BeliefGapBaseline': '0.094',
        'KLMonteCarloN': '500', 'KLMonteCarloPeriods': '5000',
        'FilterCorrelation': '0.63', 'FilterRSquared': '0.99',
        'FilterGridSize': '30', 'OTStabilityMargin': '0.3',
        'OTStabilityPct': '100', 'PayoffStationary': '0.775',
        'PayoffFiltered': '0.569', 'PayoffOverestimation': '36.3',
        'PayoffGapAbsolute': '0.094', 'PayoffGapPayoff': '0.206',
        'SRDisagreement': '37.2',
        'SRThreshold': '0.60', 'SRBeliefAfterG': '0.70',
        'SRBeliefAfterB': '0.50', 'SupermodFraction': '4',
        'SupermodTotal': '24', 'BaseAlpha': '0.3',
        'BaseAlphaFrac': '3/10', 'BaseBeta': '0.5',
        'BaseBetaFrac': '1/2', 'BasePiG': '0.625',
        'BasePiB': '0.375', 'BRThreshold': '0.40',
        'BRPayoff': '0.625', 'PaperDate': 'February 17, 2026',
    }
    stats.update(defaults)
    return stats


FIXED_PARAMS = {
    'PaperDate': 'February 17, 2026',
    'BaseAlpha': '0.3', 'BaseBeta': '0.5',
    'BasePiG': '0.625', 'BasePiB': '0.375',
    'SRBeliefAfterG': '0.70', 'SRBeliefAfterB': '0.50',
    'BRThreshold': '0.40', 'SRThreshold': '0.60', 'BRPayoff': '0.625',
    'PayoffGapAbsolute': '0.094', 'PayoffGapPayoff': '0.206',
    'KLMonteCarloN': '500', 'KLMonteCarloPeriods': '5000',
    'OTStabilityMargin': '0.3', 'FilterGridSize': '30',
}


def write_stats_tex_from_stat_lines(stats, output_path):
    """Write full stats.tex from STAT:key=value pairs plus fixed params."""
    with open(output_path, 'w') as f:
        f.write('%% Auto-generated by extract_stats.py — do not edit manually\n')
        f.write('%% Generated from analysis scripts output\n')
        f.write('%% Updated for simultaneous-move timing (C04 correction)\n\n')

        f.write('%% Paper metadata\n')
        f.write(f'\\newcommand{{\\PaperDate}}{{{FIXED_PARAMS["PaperDate"]}}}\n\n')

        f.write('%% Game parameters\n')
        for k in ['BaseAlpha', 'BaseBeta', 'BasePiG', 'BasePiB',
                   'SRBeliefAfterG', 'SRBeliefAfterB',
                   'BRThreshold', 'SRThreshold', 'BRPayoff',
                   'PayoffGapAbsolute', 'PayoffGapPayoff']:
            f.write(f'\\newcommand{{\\{k}}}{{{FIXED_PARAMS[k]}}}\n')

        f.write('\n%% Computational parameters\n')
        for k in ['KLMonteCarloN', 'KLMonteCarloPeriods',
                   'OTStabilityMargin', 'FilterGridSize']:
            f.write(f'\\newcommand{{\\{k}}}{{{FIXED_PARAMS[k]}}}\n')

        f.write('\n%% Formulas\n')
        f.write('\\newcommand{\\BeliefGapFormula}'
                '{\\frac{2\\alpha\\beta|1-\\alpha-\\beta|}{(\\alpha+\\beta)^2}}\n')

        f.write('\n%% Legacy macros (aliased from analysis output)\n')
        aliases = {
            'TVMean': 'statTvMean', 'BeliefGapBaseline': 'statGapBaseline',
            'PayoffStationary': 'statPayoffStationary',
            'PayoffFiltered': 'statPayoffFiltered',
            'PayoffOverestimation': 'statOverestimationPct',
            'SRDisagreement': 'statSrDisagreementPct',
            'OTStabilityPct': 'statOtStablePct',
            'FilterCorrelation': 'statFilterCorrelation',
            'SupermodFraction': 'statSupermodValid',
            'SupermodTotal': 'statSupermodTotal',
        }
        for display_name, stat_name in aliases.items():
            f.write(f'\\newcommand{{\\{display_name}}}{{\\{stat_name}}}\n')

        f.write('\n%% Auto-extracted statistics from analysis scripts\n')
        for key in sorted(stats.keys()):
            cmd_name = sanitize_key(key)
            val = stats[key]
            val_safe = val.replace('_', r'\_').replace('%', r'\%').replace('&', r'\&')
            f.write(f'\\newcommand{{\\{cmd_name}}}{{{val_safe}}}\n')

    print(f"Generated {output_path} with {len(stats)} extracted + {len(FIXED_PARAMS)} fixed macros")
    for key in sorted(stats.keys()):
        print(f"  \\{sanitize_key(key)} = {stats[key]}")


def write_stats_tex_legacy(stats, output_path):
    """Write stats.tex in legacy format."""
    lines = [
        '% Auto-generated statistics macros',
        '% Generated by scripts/extract_stats.py',
        '% Do not edit manually --- rerun extract_stats.py to update',
        '',
    ]
    for k, v in sorted(stats.items()):
        lines.append(f'\\newcommand{{\\{k}}}{{{v}}}')
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print(f"Wrote {len(stats)} statistics to {output_path}")


def main():
    parser = argparse.ArgumentParser(description='Extract stats from analysis output')
    parser.add_argument('stats_file', nargs='?', default=None,
                        help='Path to stats_raw.txt (or read from stdin)')
    parser.add_argument('--workspace', default=None,
                        help='Legacy: path to Agent1206_workspace directory')
    parser.add_argument('--output', default=None,
                        help='Output path for stats.tex')
    args = parser.parse_args()

    output = args.output or os.path.join(os.path.dirname(__file__), '..', 'stats.tex')

    if args.workspace:
        # Legacy mode: read from SA report files
        stats = extract_from_workspace(os.path.abspath(args.workspace))
        write_stats_tex_legacy(stats, os.path.abspath(output))
    elif args.stats_file and os.path.isfile(args.stats_file):
        # New mode: read STAT: lines from file
        with open(args.stats_file, 'r') as f:
            lines = f.readlines()
        stats = extract_from_stat_lines(lines)
        write_stats_tex_from_stat_lines(stats, os.path.abspath(output))
    else:
        # Read from stdin
        lines = sys.stdin.readlines()
        stats = extract_from_stat_lines(lines)
        write_stats_tex_from_stat_lines(stats, os.path.abspath(output))


if __name__ == '__main__':
    main()
